name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 11 环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: "x64"  # 确保64位架构
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --console --name MyApp --clean --distpath dist main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-Windows
        path: dist/MyApp.exe
